"""Add query_versions table and update queries

Revision ID: 0b342fc69676
Revises: d9d9ea7fdbdd
Create Date: 2025-06-25 21:44:03.765459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b342fc69676'
down_revision = 'd9d9ea7fdbdd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sql_template', sa.Text(), nullable=False),
    sa.Column('params_info', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_id', 'version_number', name='uq_query_version')
    )
    op.create_index(op.f('ix_query_versions_id'), 'query_versions', ['id'], unique=False)
    op.create_index(op.f('ix_query_versions_query_id'), 'query_versions', ['query_id'], unique=False)
    op.add_column('queries', sa.Column('current_version_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'queries', 'query_versions', ['current_version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'queries', type_='foreignkey')
    op.drop_column('queries', 'current_version_id')
    op.drop_index(op.f('ix_query_versions_query_id'), table_name='query_versions')
    op.drop_index(op.f('ix_query_versions_id'), table_name='query_versions')
    op.drop_table('query_versions')
    # ### end Alembic commands ###